[package]
name = "no-std"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
eyra = { path = "../..", default-features = false }
rustix-dlmalloc = { version = "0.1.0", features = ["global"] }

# This is just an example crate, and not part of the eyra workspace.
[workspace]
